# Generated by Django 6.0.5 on 2026-05-30 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='eliminado_por',
            field=models.ManyToManyField(blank=True, related_name='chats_eliminados', to=settings.AUTH_USER_MODEL),
        ),
    ]
