# Generated by Django 6.0.3 on 2026-06-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.PositiveIntegerField()),
                ('colonia', models.CharField(max_length=100)),
                ('alcaldia', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('tipo_renta', models.CharField(choices=[('solo_mujeres', 'Solo mujeres'), ('solo_hombres', 'Solo hombres'), ('mixto', 'Mixto')], default='mixto', max_length=20)),
                ('cuartos', models.PositiveIntegerField(default=1)),
                ('amueblado', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('estacionamiento', models.BooleanField(default=False)),
                ('cocina', models.BooleanField(default=False)),
                ('metro_cercano', models.CharField(blank=True, max_length=100)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='departamentos/principal/')),
                ('disponible', models.BooleanField(default=True)),
                ('rentado_hasta', models.DateField(blank=True, null=True)),
                ('vistas_mes', models.PositiveIntegerField(default=0)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='departamentos/galeria/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Imagen de departamento',
                'verbose_name_plural': 'Imágenes de departamento',
                'db_table': 'departamentos_imagenes',
                'ordering': ['orden'],
            },
        ),
    ]
