# Generated by Django 6.0.5 on 2026-05-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.IntegerField()),
                ('colonia', models.CharField(max_length=100)),
                ('alcaldia', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('tipo_renta', models.CharField(choices=[('solo_mujeres', 'Solo mujeres'), ('solo_hombres', 'Solo hombres'), ('mixto', 'Mixto')], default='mixto', max_length=20)),
                ('cuartos', models.IntegerField(default=1)),
                ('amueblado', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('estacionamiento', models.BooleanField(default=False)),
                ('cocina', models.BooleanField(default=False)),
                ('metro_cercano', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
