# Generated by Django 6.0.5 on 2026-06-06 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('ruido', 'Ruido excesivo'), ('seguridad', 'Seguridad'), ('limpieza', 'Limpieza'), ('servicios', 'Servicios'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('revisado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_realizados', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='departamentos.departamento')),
            ],
            options={
                'db_table': 'reportes',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('aspectos_positivos', models.JSONField(blank=True, default=list)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='departamentos.departamento')),
            ],
            options={
                'db_table': 'calificaciones',
                'unique_together': {('departamento', 'arrendatario')},
            },
        ),
    ]
