# Generated by Django 6.0.5 on 2026-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamento_arrendador_departamento_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='departamentos/'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='cuartos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='vistas_mes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
