# Generated by Django 6.0.5 on 2026-06-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_departamento_latitud_departamento_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
