# Generated by Django 6.0.5 on 2026-06-01 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='imagen',
        ),
        migrations.AddField(
            model_name='departamento',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='departamentos/principal/'),
        ),
        migrations.CreateModel(
            name='ImagenDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='departamentos/galeria/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Imagen de departamento',
                'verbose_name_plural': 'Imágenes de departamento',
                'db_table': 'departamentos_imagenes',
                'ordering': ['orden'],
            },
        ),
    ]
