# Generated by Django 6.0.5 on 2026-05-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
