# Generated by Django 6.0.5 on 2026-06-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
