# Generated by Django 6.0.5 on 2026-06-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_add_tipo_documento'),
        ('usuarios', '0002_usuario_tipo_documento'),
    ]

    operations = [
    ]
