# Generated by Django 6.0.5 on 2026-05-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado_verificacion',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
